<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PoojaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('poojas')->insert([
            [
                'title' => 'Mahashivratri Blessings Pooja',
                'tag' => 'Shivratri Special',
                'language' => 'en',
                'excerpt' => 'Seek divine blessings from Lord Shiva on the sacred occasion of Mahashivratri.',
                'description' => 'This special pooja is performed on Mahashivratri to invoke Lord Shiva’s blessings for spiritual growth, prosperity, and protection from negative energies.',
                'start_date' => '2025-02-26',
                'end_date' => '2025-02-26',
                'image' => '/seed/pooja/img (2).jpeg',
                'price' => 2100,
                'original_price' => 4000,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Rudra Abhishek Pooja',
                'tag' => 'Shiva Pooja',
                'language' => 'en',
                'excerpt' => 'A sacred ritual to please Lord Shiva and remove obstacles from life.',
                'description' => 'Rudra Abhishek is a powerful pooja performed to seek Lord Shiva’s divine grace, remove sins, and bring peace, success, and health into life.',
                'start_date' => '2025-03-05',
                'end_date' => '2025-03-05',
                'image' => '/seed/pooja/img (3).jpeg',
                'price' => 1100,
                'original_price' => 3000,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Wealth & Prosperity Pooja',
                'tag' => 'Wealth & Prosperity',
                'language' => 'en',
                'excerpt' => 'Attract abundance and financial growth with this special pooja.',
                'description' => 'This pooja invokes divine blessings to enhance wealth, career success, and overall prosperity, helping individuals and businesses grow financially.',
                'start_date' => '2025-03-12',
                'end_date' => '2025-03-12',
                'image' => '/seed/pooja/img (5).jpeg',
                'price' => 1111,
                'original_price' => 5151,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Kaal Sarp Dosh Nivaran Pooja',
                'tag' => 'Dosh Nivaran',
                'language' => 'en',
                'excerpt' => 'Eliminate the effects of Kaal Sarp Dosh and bring stability to life.',
                'description' => 'This pooja helps individuals suffering from Kaal Sarp Dosh, ensuring protection from obstacles, financial instability, and mental distress.',
                'start_date' => '2025-03-18',
                'end_date' => '2025-03-18',
                'image' => '/seed/pooja/img (4).jpeg',
                'price' => 1100,
                'original_price' => 2100,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pitra Dosh Pooja',
                'tag' => 'Ancestral Peace',
                'language' => 'en',
                'excerpt' => 'Honor your ancestors and remove ancestral karmic blockages.',
                'description' => 'This pooja helps in offering peace to departed ancestors, resolving Pitra Dosh, and bringing prosperity and harmony to the family.',
                'start_date' => '2025-03-22',
                'end_date' => '2025-03-22',
                'image' => '/seed/pooja/img (6).jpeg',
                'price' => 2100,
                'original_price' => 4100,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Career & Job Success Pooja',
                'tag' => 'Career Growth',
                'language' => 'en',
                'excerpt' => 'Achieve job stability and career growth with divine blessings.',
                'description' => 'This pooja is performed to remove obstacles in job, career, and business, ensuring stability, promotions, and professional success.',
                'start_date' => '2025-03-28',
                'end_date' => '2025-03-28',
                'image' => '/seed/pooja/img (7).jpeg',
                'price' => 501,
                'original_price' => 2100,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Health & Wellness Pooja',
                'tag' => 'Health & Healing',
                'language' => 'en',
                'excerpt' => 'Promote physical and mental well-being with divine intervention.',
                'description' => 'This pooja is performed to invoke blessings for good health, recovery from illness, and protection from negative health energies.',
                'start_date' => '2025-04-01',
                'end_date' => '2025-04-01',
                'image' => '/seed/pooja/img (8).jpeg',
                'price' => 701,
                'original_price' => 2500,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Manglik Dosh Nivaran Pooja',
                'tag' => 'Marriage Remedies',
                'language' => 'en',
                'excerpt' => 'Neutralize Manglik Dosh and promote harmonious marital life.',
                'description' => 'This pooja reduces the negative effects of Manglik Dosh and enhances compatibility and success in marriage.',
                'start_date' => '2025-04-05',
                'end_date' => '2025-04-05',
                'image' => '/seed/pooja/img (9).jpeg',
                'price' => 1100,
                'original_price' => 3100,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Navgraha Shanti Pooja',
                'tag' => 'Planetary Peace',
                'language' => 'en',
                'excerpt' => 'Pacify malefic planets and strengthen beneficial planetary influences.',
                'description' => 'This powerful pooja is for those facing planetary issues in their horoscope and aims to balance cosmic influences for a peaceful life.',
                'start_date' => '2025-04-10',
                'end_date' => '2025-04-10',
                'image' => '/seed/pooja/img (10).jpeg',
                'price' => 1500,
                'original_price' => 4500,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Marriage & Relationship Harmony Pooja',
                'tag' => 'Love & Relationship',
                'language' => 'en',
                'excerpt' => 'Restore love, trust, and harmony in relationships.',
                'description' => 'This pooja helps those facing challenges in marriage or relationships by invoking divine blessings for unity and affection.',
                'start_date' => '2025-04-15',
                'end_date' => '2025-04-15',
                'image' => '/seed/pooja/img (11).jpeg',
                'price' => 901,
                'original_price' => 2700,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Business Growth Pooja',
                'tag' => 'Business Success',
                'language' => 'en',
                'excerpt' => 'Boost your business success with divine blessings.',
                'description' => 'This pooja brings positive energy to your business ventures, helping with profits, stability, and expansion.',
                'start_date' => '2025-04-20',
                'end_date' => '2025-04-20',
                'image' => '/seed/pooja/img (12).jpeg',
                'price' => 1300,
                'original_price' => 4100,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Hanuman Jayanti Special Pooja',
                'tag' => 'Hanuman Jayanti',
                'language' => 'en',
                'excerpt' => 'Gain strength and protection through Lord Hanuman’s blessings.',
                'description' => 'On the occasion of Hanuman Jayanti, this pooja brings courage, protection, and victory over enemies and obstacles.',
                'start_date' => '2025-04-23',
                'end_date' => '2025-04-23',
                'image' => '/seed/pooja/img (13).jpeg',
                'price' => 801,
                'original_price' => 2000,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Chandra Grahan Special Pooja',
                'tag' => 'Eclipse Pooja',
                'language' => 'en',
                'excerpt' => 'Shield yourself from the adverse effects of lunar eclipses.',
                'description' => 'This pooja helps minimize the negative spiritual and astrological effects caused by a lunar eclipse.',
                'start_date' => '2025-04-28',
                'end_date' => '2025-04-28',
                'image' => '/seed/pooja/img (14).jpeg',
                'price' => 999,
                'original_price' => 2500,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Black Magic Protection Pooja',
                'tag' => 'Spiritual Protection',
                'language' => 'en',
                'excerpt' => 'Safeguard yourself from black magic and evil eye effects.',
                'description' => 'This powerful pooja forms a divine shield to remove and protect from dark energies, black magic, and psychic attacks.',
                'start_date' => '2025-05-03',
                'end_date' => '2025-05-03',
                'image' => '/seed/pooja/img (15).jpeg',
                'price' => 1600,
                'original_price' => 5100,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Peace & Harmony Pooja',
                'tag' => 'Calm & Clarity',
                'language' => 'en',
                'excerpt' => 'Invite peace, mental calmness, and family harmony into your life.',
                'description' => 'This pooja helps to eliminate stress, internal conflicts, and discord among family members by invoking tranquility.',
                'start_date' => '2025-05-07',
                'end_date' => '2025-05-07',
                'image' => '/seed/pooja/img (16).jpeg',
                'price' => 701,
                'original_price' => 2100,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Nakshatra Shanti Pooja',
                'tag' => 'Birth Chart Remedies',
                'language' => 'en',
                'excerpt' => 'Correct harmful nakshatra influences from your birth chart.',
                'description' => 'This pooja is tailored to the native’s birth nakshatra and helps pacify ill effects related to birth stars and planetary alignment.',
                'start_date' => '2025-05-10',
                'end_date' => '2025-05-10',
                'image' => '/seed/pooja/img (17).jpeg',
                'price' => 1800,
                'original_price' => 3700,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Graha Dosh Nivaran Pooja',
                'tag' => 'Astrological Remedies',
                'language' => 'en',
                'excerpt' => 'Balance your planets and nullify doshas in your chart.',
                'description' => 'A highly effective pooja for nullifying Graha Doshas and enhancing the positive influence of planets in one’s life.',
                'start_date' => '2025-05-13',
                'end_date' => '2025-05-13',
                'image' => '/seed/pooja/img (18).jpeg',
                'price' => 1200,
                'original_price' => 3300,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Child Blessing Pooja',
                'tag' => 'Fertility & Children',
                'language' => 'en',
                'excerpt' => 'Seek divine blessings for childbirth and healthy offspring.',
                'description' => 'This pooja is performed for couples seeking children or protection and good health for their existing children.',
                'start_date' => '2025-05-17',
                'end_date' => '2025-05-17',
                'image' => '/seed/pooja/img (19).jpeg',
                'price' => 901,
                'original_price' => 2600,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Santan Gopal Pooja',
                'tag' => 'Child Blessings',
                'language' => 'en',
                'excerpt' => 'A sacred ritual to bless childless couples with progeny.',
                'description' => 'Performed to please Lord Krishna in his infant form, this pooja aids in fertility and successful childbirth.',
                'start_date' => '2025-05-21',
                'end_date' => '2025-05-21',
                'image' => '/seed/pooja/img (20).jpeg',
                'price' => 1500,
                'original_price' => 3500,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mahamrityunjaya Jaap',
                'tag' => 'Health & Longevity',
                'language' => 'en',
                'excerpt' => 'Powerful mantra chanting for protection against untimely death.',
                'description' => 'This powerful ritual invokes Lord Shiva to overcome fear, diseases, and death. Ideal for healing, recovery, and longevity.',
                'start_date' => '2025-05-25',
                'end_date' => '2025-05-25',
                'image' => '/seed/pooja/img (21).jpeg',
                'price' => 2500,
                'original_price' => 5100,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'महाशिवरात्रि आशीर्वाद पूजा',
                'tag' => 'शिवरात्रि विशेष',
                'language' => 'hi',
                'excerpt' => 'महाशिवरात्रि के पवित्र अवसर पर भगवान शिव का दिव्य आशीर्वाद प्राप्त करें।',
                'description' => 'यह विशेष पूजा महाशिवरात्रि पर आध्यात्मिक विकास, समृद्धि और नकारात्मक ऊर्जा से सुरक्षा के लिए भगवान शिव का आशीर्वाद प्राप्त करने हेतु की जाती है।',
                'start_date' => '2025-05-25',
                'end_date' => '2025-05-25',
                'image' => '/seed/pooja/img (21).jpeg',
                'price' => 2500,
                'original_price' => 5100,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'रुद्राभिषेक पूजा',
                'tag' => 'शिव पूजा',
                'language' => 'hi',
                'excerpt' => 'भगवान शिव को प्रसन्न करने और जीवन से बाधाएं दूर करने की एक पवित्र विधि।',
                'description' => 'रुद्राभिषेक एक शक्तिशाली पूजा है जो भगवान शिव की कृपा प्राप्त करने, पापों से मुक्ति और जीवन में शांति, सफलता और स्वास्थ्य के लिए की जाती है।',
                'start_date' => '2025-05-25',
                'end_date' => '2025-05-25',
                'image' => '/seed/pooja/img (21).jpeg',
                'price' => 2500,
                'original_price' => 5100,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'धन एवं समृद्धि पूजा',
                'tag' => 'धन एवं समृद्धि',
                'language' => 'hi',
                'excerpt' => 'इस विशेष पूजा से आर्थिक वृद्धि और समृद्धि को आकर्षित करें।',
                'description' => 'यह पूजा धन, करियर में सफलता और समग्र समृद्धि को बढ़ाने के लिए दिव्य आशीर्वाद प्रदान करती है, जिससे व्यक्ति और व्यवसाय दोनों आर्थिक रूप से बढ़ते हैं।',
                'start_date' => '2025-05-25',
                'end_date' => '2025-05-25',
                'image' => '/seed/pooja/img (21).jpeg',
                'price' => 2500,
                'original_price' => 5100,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'कालसर्प दोष निवारण पूजा',
                'tag' => 'दोष निवारण',
                'language' => 'hi',
                'excerpt' => 'कालसर्प दोष के प्रभावों को समाप्त कर जीवन में स्थिरता लाएं।',
                'description' => 'यह पूजा कालसर्प दोष से पीड़ित व्यक्तियों को जीवन की बाधाओं, आर्थिक अस्थिरता और मानसिक तनाव से सुरक्षा प्रदान करती है।',
                'start_date' => '2025-05-25',
                'end_date' => '2025-05-25',
                'image' => '/seed/pooja/img (21).jpeg',
                'price' => 2500,
                'original_price' => 5100,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'पितृ दोष पूजा',
                'tag' => 'पितृ शांति',
                'language' => 'hi',
                'excerpt' => 'अपने पितरों को सम्मान दें और पूर्वजों के कर्म बंधनों को दूर करें।',
                'description' => 'यह पूजा departed पितरों की शांति के लिए, पितृ दोष को समाप्त करने और परिवार में समृद्धि एवं सौहार्द लाने हेतु की जाती है।',
                'start_date' => '2025-05-25',
                'end_date' => '2025-05-25',
                'image' => '/seed/pooja/img (21).jpeg',
                'price' => 2500,
                'original_price' => 5100,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
